/* Source and licensing information for the line(s) below can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/matchMedia.js. */
window.matchMedia=window.matchMedia||(function(doc,undefined){var bool,docElem=doc.documentElement,refNode=docElem.firstElementChild||docElem.firstChild,fakeBody=doc.createElement('body'),div=doc.createElement('div');div.id='mq-test-1';div.style.cssText="position:absolute;top:-100em";fakeBody.style.background="none";fakeBody.appendChild(div);return function(q){div.innerHTML='&shy;<style media="'+q+'"> #mq-test-1 { width: 42px; }</style>';docElem.insertBefore(fakeBody,refNode);bool=div.offsetWidth==42;docElem.removeChild(fakeBody);return{matches:bool,media:q}}})(document);;
/* Source and licensing information for the above line(s) can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/matchMedia.js. */
/* Source and licensing information for the line(s) below can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/eq.js. */
(function($){jQuery.fn.equalHeight=function(){var height=0,maxHeight=0;this.each(function(){height=jQuery(this).outerHeight();maxHeight=(height>maxHeight)?height:maxHeight});return this.each(function(){var t=jQuery(this),minHeight=maxHeight-(t.outerHeight()-t.height()),property=jQuery.browser.msie&&jQuery.browser.version<7?'height':'min-height';t.css(property,minHeight+'px')})}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/eq.js. */
/* Source and licensing information for the line(s) below can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/eq-os.js. */
(function($){Drupal.behaviors.eqOS={attach:function(context){if(matchMedia('only screen and (min-width: 1025px)').matches)$('.region-content-first .region-inner,.region-content-second .region-inner,.region-content-bottom .region-inner').equalHeight()}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/eq-os.js. */
/* Source and licensing information for the line(s) below can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/scripts.js. */
(function($){Drupal.behaviors.hwpiRemoveStuff={attach:function(context){$('ul.ui-tabs-nav').removeClass('ui-helper-clearfix')}};Drupal.behaviors.hwpiMenuToggle={attach:function(ctx){if($('.mobile-buttons',ctx).length==0)return;$('.mobile-buttons a[data-target]').each(function(){var $this=$(this),$pop=$($this.attr('data-target'));if($pop.length==0)$this.remove()});$('.mobile-buttons a[data-target]').click(function(e){var $this=$(this),$pop=$($this.attr('data-target'));if(!$pop.hasClass('opened')){$('.toggled').removeClass('toggled');$this.addClass('toggled');$('.opened').removeClass('opened');$pop.addClass('opened')}else{$('.opened').removeClass('opened');$('.toggled').removeClass('toggled')}})}}})(jQuery);;
/* Source and licensing information for the above line(s) can be found at http://chemistry.harvard.edu/profiles/openscholar/themes/hwpi_basetheme/js/scripts.js. */
